import pandas as pd
import plotly.express as px
import streamlit as st
import json

PATH_TO_DATA = "./state_city_data.json"
PATH_TO_GEOJSON = "./indian_map_coordinates.geojson"


def state_city_scatter_mapbox():
    # give subheading in the streamlit app
    st.subheader("Visualizing State and Capital of India - Scatter Map")

    # loading state and city data from JSON file into Pandas DataFrame
    state_city_data = pd.read_json(PATH_TO_DATA)

    # displays a table and hides autogenerated streamlit index column
    st.dataframe(state_city_data, hide_index=True)
    # creating a scatter mapbox plot
    fig = px.scatter_mapbox(
        data_frame=state_city_data,
        lat="lat",
        lon="long",
        # if we hover over a state then display the capital
        hover_name="state",
        hover_data=["capital"],
        # gives each capital a color
        color="capital",
        # color_discrete_sequence=px.colors.qualitative.Plotly,
        zoom=3,
        opacity=0.9,
        height=600,
        center={
            "lat": 20.59,
            "lon": 78.96
        })
    # Basemap style
    fig.update_layout(mapbox_style="carto-positron")
    # Increasing the number will make it smaller aka increases padding (space provided on screen)
    fig.update_layout(margin={"r": 0, "t": 0, "l": 0, "b": 0})
    return st.plotly_chart(fig)


def state_city_choropleth_mapbox():
    # give subheading in the streamlit app
    st.subheader("Visualizing State and Capital of India - Choropleth Map")
    # load state and city data from JSON file into Pandas DataFrame
    state_city_data = pd.read_json(PATH_TO_DATA)
    # show a table
    st.dataframe(state_city_data, hide_index=True)
    # plotly choropleth plot
    fig = px.choropleth_mapbox(
        data_frame=
        state_city_data,  # if we hover over a state then display the capital
        hover_name="state",
        hover_data=["capital"],
        geojson=json.load(open(PATH_TO_GEOJSON, "r")),
        # plotting the state with a unique color
        featureidkey="properties.ST_NM",
        locations="state",
        # gives each capital a color
        color="capital",
        # color_discrete_sequence=px.colors.qualitative.Plotly,
        zoom=3,
        opacity=0.5,
        height=700,
        labels={"capital": "Capital City"},
        center={
            "lat": 20.59,
            "lon": 78.96
        })
    fig.update_layout(mapbox_style="carto-darkmatter")
    return st.plotly_chart(fig)
